feature: kakao login api ios 수정
depromeet/ticlemoa-backend pull request #18
Opened 2022-12-07 14:15 UTC by stae1102

# 작업한 내용

카카오 로그인 api를 iOS에서 사용할 수 있도록 수정했습니다.
과정은 아래 사진과 같습니다.
> iOS 팀과 논의하여 과정이 맞는지 검증완료했습니다.

![image](https://user-images.githubusercontent.com/83271772/206194864-20481504-6ef6-4fca-adb4-5024e5c0fa65.png)

🆑: 클라이언트 측
🅱️: 백엔드 측

🆑카카오 로그인 요청 -> 🆑카카오톡 어플로 이동해 유저가 동의화면에서 동의하여 로그인 체크 -> 회원 데이터 생성 -> 클라이언트로 액세스 토큰 발급 -> 🆑발급 받은 토큰을 서버로 송신 -> 🅱️해당 액세스 토큰을 통해 카카오 서버로 회원 조회 요청 -> 🅱️해당 유저 데이터를 수신 -> 🅱️데이터가 DB에 있으면 로그인/없으면 회원가입 -> 🆑티클모아 서버의 액세스 토큰을 클라이언트로 전송받음

## 로그인 처리 과정

### 🆑 발급 받은 토큰을 서버로 송신 -> 서버 수신 과정
```ts
// auth.controller.ts
  @Post('kakao/login')
  async kakaoLogin(@Body() kakaoData: LoginRequest, @Res({ passthrough: true }) res: Response): Promise<AccessToken> {
    const { accessToken, refreshToken } = await this.authService.login(kakaoData);

    res.cookie('refresh_token', refreshToken, {
      httpOnly: true,
      maxAge: +this.configService.get('JWT_REFRESH_TOKEN_EXPIRATION_TIME') * 1000,
    });
    return { accessToken };
  }
```

```ts
// login-request.dto.ts
export class LoginRequest {
  accessToken!: string;

  vendor!: string;
}
```

```ts
// token-response.interface.ts
export interface TokenResponse extends AccessToken, RefreshToken {}

export interface AccessToken {
  accessToken: string;
}

export interface RefreshToken {
  refreshToken: string;
}
```

### 🅱️ 해당 액세스 토큰을 통해 카카오 서버로 회원 조회, 🅱️ 해당 유저 데이터를 수신

```ts
// auth.service.ts
async login(data: LoginRequest): Promise<TokenResponse> {
    let userId: number;
    switch (data.vendor) {
      case 'kakao': {
        userId = await this.getUserByKakaoAccessToken(data.accessToken);
```

```ts
// auth.service.ts
  async getUserByKakaoAccessToken(accessToken: string): Promise<number> {
    const user = await axios.get('https://kapi.kakao.com/v2/user/me', {
      headers: { Authorization: `Bearer ${accessToken}` },
    });

    if (!user) {
      throw new BadRequestException({
        message: '카카오 로그인에 실패했습니다',
        statusCode: HttpStatus.BAD_REQUEST,
      });
    }
    const snsId = String(user.data.id);
    const existedUser = await this.userRepository.findBySnsId(snsId);

    if (!existedUser) {
      const { nickname, profile_image: avatarUrl } = user.data.properties;
      const kakaoAccount = user.data.kakao_account;
      const email = kakaoAccount.has_email && !kakaoAccount.email_needs_agreement ? kakaoAccount.email : null;
      const { id } = await this.userRepository.createUser({
        snsId,
        email,
        nickname,
        avatarUrl,
        provider: AuthProvider.kakao,
      });
      return id;
    }

    return existedUser.id;
  }
```

### 🅱️ 데이터가 DB에 있으면 로그인/없으면 유저 생성

```ts
// user.repository.ts
  async findBySnsId(snsId: string) {
    return await this.findOne({ where: { snsId } });
  }

  async createUser(userData: Partial<User>) {
    const createdUser = this.create(userData);
    await this.save(createdUser);
    return createdUser;
  }
```

2022-12-07 14:34 UTC, stae1102 commented
# repository의 인자 타입을 변경

```ts
// user.repository.ts
  async findBySnsId(snsId: string) {
    return await this.findOne({ where: { snsId } });
  }

  async createUser(userData: Partial<User>) {
    const createdUser = this.create(userData);
    await this.save(createdUser);
    return createdUser;
  }
```

2022-12-10 04:22 UTC, be-student requested changes
잘 봤습니다

2022-12-10 04:22 UTC, be-student commented on src/auth/auth.service.ts
> +      }
이 부분을 조금 명확하게 해주면 좋을 것 같아요
undefined or default 2개중 하나 제거하는 쪽이 좋아보여요

2022-12-10 04:22 UTC, be-student commented on src/auth/auth.service.ts
> +    const [accessToken, refreshToken] = await Promise.all([
그냥 sign으로 안 되는 이유를 찾아주세요

2022-12-10 04:22 UTC, be-student commented on src/auth/dto/login-request.dto.ts
> +  accessToken!: string;
무조건 보장 되나요?

2022-12-10 04:22 UTC, be-student commented on src/entities/user.entity.ts
> +  @IsNumber()
IsNumber 같은 것들을 단 이유가 있나요
어차피 controller에서는 dto로 검증할 테니까요

2022-12-10 04:22 UTC, be-student commented on src/user/dto/create-user.dto.ts
> +  snsId: string;
IsNumber 같은 부분은 이쪾에서 다는 게 좋아보여요

2022-12-10 04:22 UTC, be-student commented on src/user/repository/user.repository.ts
> +  async findBySnsId(snsId: string) {
findOneBySnsId

2022-12-10 04:23 UTC, stae1102 commented on src/auth/auth.service.ts
> +      }
제거 완료

2022-12-10 04:40 UTC, be-student requested changes
고쳐주세요

2022-12-10 04:40 UTC, be-student commented on src/entities/user.entity.ts
>    @IsString()
이런 부분들 다 없애주세요

2022-12-10 04:42 UTC, be-student requested changes
고쳐주세요

2022-12-10 04:42 UTC, be-student commented on src/entities/user.entity.ts
>    @IsEmail()
이런 부분들도 다 없애주세요

2022-12-10 05:32 UTC, stae1102 commented on src/entities/user.entity.ts
>    @IsEmail()
class validating 겹치는 내용 삭제했습니다~ 감사합니다

2022-12-10 06:49 UTC, Yaminyam approved these changes
작업 하면서 꾸준히 type 명시하면서 리팩토링 하는게 훌륭하십니다

2022-12-10 06:51 UTC, stae1102 commented
# enum을 union type으로 변경

```ts
export const AuthProvider = {
  KAKAO: 'KAKAO',
  GOOGLE: 'GOOGLE',
  NAVER: 'NAVER',
  APPLE: 'APPLE',
} as const;

export type AuthProvider = typeof AuthProvider[keyof typeof AuthProvider];
```

# jwt payload의 타입을 user 도메인 엔티티로 지정한 것을 수정

```ts
import { IsNotEmpty, IsNumber } from 'class-validator';

export class jwtPayload {
  @IsNumber()
  @IsNotEmpty()
  id: number;
}
```

2022-12-10 06:52 UTC, stae1102 commented
> 작업 하면서 꾸준히 type 명시하면서 리팩토링 하는게 훌륭하십니다

2022-12-10 06:53 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
save()로 update와 create를 동시에 처리 하지 않고 나누신 이유가 있으신가요?

2022-12-10 06:56 UTC, stae1102 commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
이게 아마 저때 각각 반환되는 값 확인해보려고 한 것 같아요

2022-12-10 06:57 UTC, stae1102 commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
# Before
```ts
  async createUser(createUserDto: CreateUserDto): Promise<User> {
    const createdUser: User = this.create(createUserDto);
    await this.save(createdUser);
    return createdUser;
  }
```

# After
```ts
  async createUser(createUserDto: CreateUserDto): Promise<User> {
    return await this.save(createUserDto);
  }
```
이렇게 바꿔볼까요?

2022-12-10 07:02 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
save는 없으면 insert 있으면 update 해주는애라서 무조건 앞에 select 후에 insert 할 지 update 할지를 결정합니다
무조건 create 하는 함수라면 create만 하는게 좋지않을까요?

2022-12-10 07:09 UTC, stae1102 commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
아아 save가 upsert 역할을 해주는 역할이군요

오 근데 create만 하고 return 하면 dataGrip 보니까 로우가 안 생기던데 어떻게 하는지 알려주실 수 있을까요??

2022-12-10 07:11 UTC, stae1102 commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
오 시온님 이렇게 바꿔봤어요

```ts
  async createUser(createUserDto: CreateUserDto): Promise<User> {
    const createdUser = this.create(createUserDto);
    await this.insert(createdUser);
    return createdUser;
  }
```

2022-12-10 07:19 UTC, be-student approved these changes

2022-12-10 07:25 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
https://github.com/typeorm/typeorm/issues/1789

2022-12-10 07:26 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
그냥 insert만 해도 안들어가나요?

2022-12-10 07:35 UTC, stae1102 commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
insert해도 들어가긴 하네요!

반환하는 타입이 InsertResult라서 이런 식으로 바꾸니까 됐습니다.

# Before

```ts
// user.repository.ts
  async createUser(createUserDto: CreateUserDto): Promise<User> {
    const createdUser = this.create(createUserDto);
    await this.insert(createdUser);
    return createdUser;
  }
```

```ts
// auth.service.ts
      const { id } = await this.userRepository.createUser({
        snsId,
        email,
        nickname,
        avatarUrl,
        provider: AuthProvider.KAKAO,
      });
      return id;
    }
```

# After

```ts
// user.repository.ts
  async createUser(createUserDto: CreateUserDto): Promise<InsertResult> {
    return await this.insert(createUserDto);
  }
```

```ts
      const createdUser = await this.userRepository.createUser({
        snsId,
        email,
        nickname,
        avatarUrl,
        provider: AuthProvider.KAKAO,
      });
      return createdUser.raw.id;
    }
```

2022-12-10 07:35 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
그리고 creatUser로 함수를 만들면 사용 할때
userRepository.createUser()의 형태가 되게되는데 해당 함수 없이 그냥 user.service에서 기본 Repository 함수 사용해도 되지 않나 싶네영

2022-12-10 07:37 UTC, Yaminyam commented on src/auth/auth.service.ts
> +      const { id } = await this.userRepository.createUser({
아하 type이 insertUser 타입이라 새로 정의를 해주신거군요
어짜피 유저를 생성하는게 저곳에서밖에없는데 그러면 새로운 타입을 만들지 않고도 user.schema에서 없는 친구들을 어선셜로 선언해도 되지않나 싶네요
어떤게 더 좋은 방식인진 잘 모르겠군요

2022-12-10 08:17 UTC, merged