feat: 태그 생성 api
depromeet/ticlemoa-backend pull request #30
Opened 2022-12-14 09:45 UTC by stae1102

# 작업한 내용

- 태그 리소스 파일 생성
- 태그 엔티티 생성
- 태그 레포지터리 생성
- 태그 생성 API 구현
- 요청, 응답 등 DTO 추가

# 작업 내용 사진

## API 응답 확인

![image](https://user-images.githubusercontent.com/83271772/207552226-646feaff-7db7-423f-b22b-edca4cb25d8a.png)

## DB 값 생성 확인

<img width="993" alt="image" src="https://user-images.githubusercontent.com/83271772/207552388-3cc6b4fe-e0ce-4e1f-bb6d-5bc16cccf76a.png">

## swagger 추가

<img width="953" alt="image" src="https://user-images.githubusercontent.com/83271772/207552488-32172977-c20d-4b5a-8945-483223511a0b.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/83271772/207552556-c108079e-0c11-4f62-8cad-501f298f2dd5.png">

# 궁금한 점

- 트랜잭션이 갱신(수정, 삭제)하는 메서드가 하나일 때도 적용하는 것이 좋은지 궁금합니다.
- 응답 DTO 작성하는 방법이 궁금했습니다.

2022-12-14 15:30 UTC, be-student requested changes
1차 리뷰 했습니다!

2022-12-14 15:30 UTC, be-student commented on src/entities/article.entity.ts
>    @ManyToOne(() => User, (user) => user.articles)
이거 왜 바꾸셨나요

2022-12-14 15:30 UTC, be-student commented on src/entities/tag.entity.ts
> +  @ApiProperty({ example: '디프만', description: '태그 내용' })
entity는 api property 가 있으면 안됩니다
dto에만 있어야 합니다

2022-12-14 15:30 UTC, be-student commented on src/tag/dto/create-tag.dto.ts
> +  tagName: string;
태그 이름은 비어도 되나요?

2022-12-14 15:30 UTC, be-student commented on src/tag/dto/response-tag.dto.ts
> +  @ApiProperty({ nullable: true })
deleted at 이 클라이언트에 넘어가나요?
아마 알아서 필터링되어서 안 넘어갈거에요

2022-12-14 15:30 UTC, be-student commented on src/tag/repository/tag.repository.ts
> +    const existedTag: Tag = await this.findOne({ where: { tagName: createTagDto.tagName } });
태그는 유저별로 같은 이름이라도 다르게 생성되어야 되지 않나요?
이름만으로 검색하는 것 같아서요

2022-12-14 15:35 UTC, stae1102 commented on src/entities/tag.entity.ts
> +  @ApiProperty({ example: '디프만', description: '태그 내용' })
아 그렇군요 감사합니다! 수정하겠습니다~~ 강의에서는 이렇게 적길래 적어봤어요

2022-12-14 15:35 UTC, stae1102 commented on src/entities/article.entity.ts
>    @ManyToOne(() => User, (user) => user.articles)
아 이거 컬럼끼리 모아서 보려고 위로 올렸다가 같이 저장됐네요 수정했습니다!

2022-12-14 15:39 UTC, stae1102 commented on src/tag/dto/create-tag.dto.ts
> +  tagName: string;
@be-student 이거 컨트롤러에서 tagName 미리 검사한 뒤라서 여기에는 안 붙였어요!

2022-12-14 15:42 UTC, be-student requested changes

2022-12-14 15:42 UTC, be-student commented on src/tag/dto/create-tag.dto.ts
> +  tagName: string;
그럼 반대로 위쪽에 @IsNumber 같은 태그가 있으면 안된다고 생각합니다!

2022-12-14 15:52 UTC, stae1102 commented on src/tag/dto/response-tag.dto.ts
> +  @ApiProperty({ nullable: true })
![image](https://user-images.githubusercontent.com/83271772/207642749-e48ccdb9-d405-4ca7-be79-e9bde1468c03.png)

save 메서드가 이렇게 정보를 반환하길래 일단 반환되는 값을 다 넣어봤었습니다 혹시 save에서 필터링하는 방법이 있을까요??

2022-12-14 15:54 UTC, stae1102 commented on src/tag/dto/create-tag.dto.ts
> +  tagName: string;
음 그렇군요 jwtguard 통과하면서 id 넘어오는 게 보장이 되네요 또 실수했네요 ㅠㅜ 감사합니다!!

2022-12-14 15:55 UTC, stae1102 commented on src/tag/repository/tag.repository.ts
> +    const existedTag: Tag = await this.findOne({ where: { tagName: createTagDto.tagName } });
오 일단 다시보니까 검사하는 메서드에서 유저 아이디를 같이 where에서 검사해야겠네요 감사합니다

2022-12-14 16:01 UTC, be-student commented on src/tag/dto/response-tag.dto.ts
> +  @ApiProperty({ nullable: true })
@Column({select:false})
를 주면 선택이 안 되는걸로 알고 있어요

수정하시는 김에 제 article쪽도 넣어주시죠

2022-12-17 17:56 UTC, Yaminyam approved these changes

2022-12-17 17:56 UTC, Yaminyam commented on src/tag/repository/tag.repository.ts
> +  async createOneTag(userId: number, createTagRequestDto: CreateTagRequestDto): Promise<Tag> {
tagRepository 에서 사용할거니 함수명에서는 Tag를 빼도 되지 않을까요

2022-12-17 17:56 UTC, Yaminyam commented on src/tag/tag.controller.spec.ts
> +});
벌써 테스트코드까지 짜시는건가요 ㅋㅋㅋ

2022-12-18 03:08 UTC, be-student approved these changes

2022-12-18 04:21 UTC, stae1102 commented on src/tag/repository/tag.repository.ts
> +  async createOneTag(userId: number, createTagRequestDto: CreateTagRequestDto): Promise<Tag> {
오 감사합니다 수정했습니다

2022-12-18 04:37 UTC, stae1102 commented on src/tag/tag.controller.spec.ts
> +});
ㅋㅋㅋ기본으로 만든 거 안 삭제했네요 삭제해둘게여

2022-12-18 04:42 UTC, merged