feat: 태그 수정 api
depromeet/ticlemoa-backend pull request #33
Opened 2022-12-19 04:10 UTC by stae1102

# 작업한 내용

태그 수정 api를 구현했습니다.

## api 사용 사진

### postman 요청 응답

![image](https://user-images.githubusercontent.com/83271772/208345691-ff368c14-75ca-4ff4-a596-d71274e4d1ea.png)

### datagrip으로 데이터 수정됐는지 확인

![image](https://user-images.githubusercontent.com/83271772/208345725-edb387fc-d5b6-4a37-9a78-73413724a283.png)

### 존재하지 않는 태그 수정이 요청됐을 때

<img width="845" alt="image" src="https://user-images.githubusercontent.com/83271772/208345870-717765f3-0e83-405f-ad85-466f270fb69d.png">

### 경로에 유효하지 않은 값이 들어왔을 때

<img width="847" alt="image" src="https://user-images.githubusercontent.com/83271772/208345914-7286a3da-7483-425c-ab42-d8cfbf8d9253.png">

2022-12-19 07:00 UTC, be-student commented
merge conflict 해결해주세요

2022-12-19 08:12 UTC, stae1102 commented
> merge conflict 해결해주세요

네네 감사합니다 ㅎㅎ 조회 병합하면 한 번에 수정해도 될까요?

2022-12-19 16:14 UTC, be-student requested changes
잘 봤습니다
궁금한 점은
Mapper를 쓰는 이유가 뭔지가 궁금해요

2022-12-19 16:14 UTC, be-student commented on src/tag/dto/pagination/pagination-request.dto.ts
> +  @Type(() => Number)
이 부분 제거 부탁드려요

2022-12-19 16:14 UTC, be-student commented on src/tag/tag.controller.ts
> +  @ApiOkResponse({
이 부분도 안쪽으로 부탁드려요

2022-12-20 00:04 UTC, stae1102 commented on src/tag/dto/pagination/pagination-request.dto.ts
> +  @Type(() => Number)
네넵 감사합니다~ 파이프 설정도 추가했습니다!

2022-12-20 00:13 UTC, stae1102 commented on src/tag/tag.controller.ts
> +  @ApiOkResponse({
네 수정하겠습니다

2022-12-20 00:13 UTC, stae1102 commented
> 잘 봤습니다 궁금한 점은 Mapper를 쓰는 이유가 뭔지가 궁금해요

네네 저번에 알려주신 column: false 이거 엔티티에 적용해봤는데 queryBuilder나 find 작업에서만 제외가 되더라고요 그래서 은우님 코드 참고해서 원하는 컬럼만 보여주게 하고 여러 군데 재사용하려고 만들었습니다!

2022-12-20 05:23 UTC, Yaminyam approved these changes
dto가 더 상세하게 나뉘어진것 같아서 좋은것 같네요

2022-12-20 06:26 UTC, be-student approved these changes

2022-12-20 07:30 UTC, merged